name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master # Menjalankan workflow baik di branch main maupun master

# Memberikan izin untuk menulis (write) ke GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Folder hasil kompilasi Vite
          branch: gh-pages # Branch tujuan untuk hasil build statis
